/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idmgui;

import java.awt.Color;

/**
 *
 * @author Anshal Dwivedi
 */
public class DownloadOption extends javax.swing.JFrame{

    /**
     * Creates new form DownloadOption
     */
    public DownloadOption() {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        this.setLocationRelativeTo(null);
        this.setTitle("Download Manager");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleDownloadbutton = new javax.swing.JButton();
        newDownloadbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        webcrawler = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scheduleDownloadbutton.setBackground(new java.awt.Color(144, 176, 235));
        scheduleDownloadbutton.setForeground(new java.awt.Color(255, 255, 255));
        scheduleDownloadbutton.setText("Schedule Download");
        scheduleDownloadbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));
        scheduleDownloadbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scheduleDownloadbuttonMousePressed(evt);
            }
        });
        scheduleDownloadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleDownloadbuttonActionPerformed(evt);
            }
        });

        newDownloadbutton.setBackground(new java.awt.Color(144, 176, 235));
        newDownloadbutton.setForeground(new java.awt.Color(255, 255, 255));
        newDownloadbutton.setText("New Download");
        newDownloadbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));
        newDownloadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDownloadbuttonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/anshal/finadow/lo.png")); // NOI18N

        webcrawler.setBackground(new java.awt.Color(144, 176, 235));
        webcrawler.setForeground(new java.awt.Color(255, 255, 255));
        webcrawler.setText("Web Crawler");
        webcrawler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));
        webcrawler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webcrawlerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("L M Mono Caps10", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("download manager");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newDownloadbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webcrawler, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleDownloadbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(scheduleDownloadbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(newDownloadbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(webcrawler, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newDownloadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDownloadbuttonActionPerformed
        // TODO add your handling code here:\
        UrlFrame uf=new UrlFrame();
        uf.setVisible(true);
        uf.getContentPane().setBackground(Color.DARK_GRAY);
      
        
    }//GEN-LAST:event_newDownloadbuttonActionPerformed

    private void scheduleDownloadbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleDownloadbuttonMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_scheduleDownloadbuttonMousePressed

    private void scheduleDownloadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleDownloadbuttonActionPerformed
        // TODO add your handling code here:
        ScheduleFrame sf=new ScheduleFrame();
        sf.setVisible(true);
    }//GEN-LAST:event_scheduleDownloadbuttonActionPerformed

    private void webcrawlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webcrawlerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_webcrawlerActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton newDownloadbutton;
    private javax.swing.JButton scheduleDownloadbutton;
    private javax.swing.JButton webcrawler;
    // End of variables declaration//GEN-END:variables
}
