/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idmgui;

import static finadow.MainClass.download_count;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Anshal Dwivedi
 */
public class UrlFrame extends javax.swing.JFrame {

    /**
     * Creates new form UrlFrame
     */
  //  JTabbedPane tabbedPane = new JTabbedPane();
    
    ImageIcon icon = new ImageIcon("/home/anshal/finadow/dmd.png");

    public static int extension_indicator;
    public static String File_name;
    public UrlFrame() {
    
        initComponents();
        this.setBackground(Color.DARK_GRAY);
        this.setLocationRelativeTo(null);
        this.setTitle("Download Manager");
    }
   
////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        UrlField = new javax.swing.JTextField();
        tabbedpane = new javax.swing.JTabbedPane();
        spvalue = new javax.swing.JComboBox();
        spmode = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Url:-");

        startButton.setBackground(new java.awt.Color(144, 176, 235));
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Start Download");
        startButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        UrlField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tabbedpane.setBackground(java.awt.Color.darkGray);
        tabbedpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabbedpane.setForeground(new java.awt.Color(255, 255, 255));

        spvalue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "5", "10", "50", "100", "500" }));

        spmode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KbPs", "MbPs" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UrlField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int i=1;
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
     /*    File theFile=new File("/home/anshal/IdmDownloads");
        if(!theFile.exists())
        {
            theFile.mkdirs();
        }*/
        String spm=spmode.getSelectedItem().toString();
        String spv=spvalue.getSelectedItem().toString();
        
        String s=UrlField.getText();
        if(s.charAt(s.length()-1)=='/')
            s=s.substring(0,s.length()-1);
        //System.out.println("ssd"+s);
        if(s.equals(""))
        {
            ErrorPopup ep=new ErrorPopup();
            ep.setVisible(true);
        }
        else
        {
        int l=s.length();
        char a[]=new char[4];
        char b[]=new char[4];
        char c[]=new char[3000];
        
        int j=3;
        for(i=0;i<3000;i++)
        {
            c[i]=' ';
        }
        boolean flag=false;
        char p;
        i=1;
        while(l-i>=0&&s.charAt(l-i)!='/')
        {
          c[i-1]=s.charAt(l-i);
          i++;
        }
         int name_length=i-1;
         char d[]=new char[name_length];
        i=1;
        while(i<5&&i<l)
        {
            
           
                p=s.charAt(l-i);
            a[j--]= p;
            if(s.charAt(l-i-1)=='.')
                break;
            i++;

        }
        int k=0;
        if((i==5&&s.charAt(l-i)=='.')||i<5)
        {
            flag=true;
           
            for(i=j+1;i<4;i++)
                b[k++]=a[i];

        }
        
        while(k<4)
        {
            b[k++]=' ';
        }
         //int c_length=c.length;
         j=0;
         for(i=name_length;i>=0;i--)
         { 
             if(c[i]!=' ')
            {
               d[j++]=c[i]; 
            }

         }
        
         
         String homeDir = System.getProperty("user.home");

        String extension=new String(b);
      File_name=new String(d);
            System.out.println(d);   
           // System.out.println(d);
        extension=extension.toLowerCase();
            if(flag==false)
            {
               // System.out.println("anshal");
                File categoryFolder=new File(homeDir+"/Downloads/Idm_Downloads/Others");
                    if(!categoryFolder.exists())
                    {
                       categoryFolder.mkdirs();
                    }
                    extension_indicator=0;

            }
            // System.out.println("ext"+extension);
              
            //Checking for Document type File
                if(extension.equals("pdf ")||extension.equals("doc ")||extension.equals("docx")
             ||extension.equals("pub ")||extension.equals("shs ")||extension.equals("sh  ")||extension.equals("ppt ")
                        ||extension.equals("tex ")||extension.equals("txt "))
                {
                    //System.out.println("klklklk");
                    File categoryFolder=new File(homeDir+"/Downloads/Idm_Downloads/Documents");
                    if(!categoryFolder.exists())
                    {
                        //System.out.println("asaa");
                       categoryFolder.mkdirs();
                    }
                    extension_indicator=1;
                }
               //Checking For Music Files
                
                else if(extension.equals("mp3 ")||extension.equals("ogg ")||extension.equals("mv3 ")
             ||extension.equals("wav ")||extension.equals("gp3 ")||extension.equals("aac ")||extension.equals("avr ")
                        ||extension.equals("zab ")||extension.equals("cda "))
                {
                    //System.out.println("klklklk");
                    File categoryFolder=new File(homeDir+"/Downloads/Idm_Downloads/Music");
                    if(!categoryFolder.exists())
                    {
                       // System.out.println("asaa");
                       categoryFolder.mkdirs();
                    }
                    extension_indicator=2;
                }
                //checking for videos
                 else if(extension.equals("mp4 ")||extension.equals("mov ")||extension.equals("avi ")
             ||extension.equals("flv ")||extension.equals("mkv ")||extension.equals("3gpp"))
                {
                    //System.out.println("klklklk");
                    File categoryFolder=new File(homeDir+"/Downloads/Idm_Downloads/Videos");
                    if(!categoryFolder.exists())
                    {
                     //   System.out.println("asaa");
                       categoryFolder.mkdirs();
                    }
                    extension_indicator=3;
                }
                //Checkingfor Picture files
                 else if(extension.equals("jpg ")||extension.equals("gif ")||extension.equals("png ")
             ||extension.equals("icon")||extension.equals("icns")||extension.equals("tif"))
                {
                    //System.out.println("klklklk");
                    File categoryFolder=new File(homeDir+"/Downloads/Idm_Downloads/Pictures");
                    if(!categoryFolder.exists())
                    {
                     //   System.out.println("asaa");
                       categoryFolder.mkdirs();
                    }
                    extension_indicator=4;
                }
                 else{
                     File categoryFolder=new File(homeDir+"/Downloads/Idm_Downloads/Others");
                    if(!categoryFolder.exists())
                    {
                     //   System.out.println("asaa");
                       categoryFolder.mkdirs();
                    }
                    extension_indicator=0;
                     
                 }
                System.out.println(extension);
                if(!s.substring(0,4).equals("http"))
                    s="http://"+s;
                
                final String url=s;
        Runnable runer;
        runer = new Runnable() {
            
           
            @Override
            public void run() {
               // JComponent jp=new JPanel();
               jpanel  ps=new jpanel(url,extension_indicator,File_name);
              ps.setVisible(true);
              // ps.setBackground(Color.DARK_GRAY);
                tabbedpane.addTab("Download"+download_count, ps);
                
                JLabel jl=new JLabel();
                jl.setText("x");
                tabbedpane.setSelectedIndex(download_count-1);
                tabbedpane.setMnemonicAt(0, KeyEvent.VK_1);
               // tabbedpane.setComponentAt(download_count,getLabel());
              //  tabbedpane.setIconAt(0, icon);
               download_count++;
             //   ps.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            }   
        };
        Thread t=new Thread(runer, "ads");
        t.start();
        
    }//GEN-LAST:event_startButtonActionPerformed

 
    /**
     * @param args the command line arguments
     */
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField UrlField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox spmode;
    private javax.swing.JComboBox spvalue;
    public static javax.swing.JButton startButton;
    public static javax.swing.JTabbedPane tabbedpane;
    // End of variables declaration//GEN-END:variables


}


